CrmSite/Controllers/HomeController.cs
using CrmSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CrmSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrmSite/ViewComponents/user/TeachersViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CrmSite.ViewComponents.user
{
    public class TeachersViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            BLL.TeacherBLL bll = new BLL.TeacherBLL();
            return View("_teachers",bll.read());
        }
    }
}

CrmSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">milad mohseni monfared</a>.</p>
</div>

@await Component.InvokeAsync("Teachers")